## Machine Learning

* Turning things (data) into numbers & finding patterns in those numbers.

* Deep Learning - Subset of Machine Learning

* If you can build a **simple rule-based** system that doesn't requirie ML, do that.

## Deep Learning

* Good for:
    * Problems with long lists of rules
        * When traditional approach fails, ML/DL will help.
    * Continually changing environments
        * Deep Learning can adapt/learn new scenarios.
    * Discovering insights within large collections of data
    
* Not good for:
    * Need explainability
        * Patterns learnt by DL model are typically uninterpretable by a human.
    * When traditional approach is a better option
    * When errors are unacceptable
    * When don't have much data
    
    
## Machine Learning vs Deep Learning

**Not absolute**
* Machine Learning - Structured data
    * Tables (rows & columns)
    * XGBoost is typically the best algorithm, but there are exceptions.
* Deep Learning - Unstructured data
    * Random text, all over  the place.
    * Voices, images, etc.
    
## What are Neural Networks?

1. Inputs of Unstructured Data
2. Numerical Encoding
3. Pass through a Neural Network
    * Input Layer
    * Hidden Layers
    * Output Layer
4. Representation numerical outputs that we can use
5. Convert to Outputs that human can understand

## Types of Learning
* Supervised Learning (Data & Labels)
* Unsupervised & Self-supervised Learning (Data with No Labels)
* Transfer Learning

## Pytorch

* Deep Learning Framework
* Fast deep learning code in Python (able to run on GPU(s))
* Access many pre-built deep learning models (Torch Hub/ torchvision.models)
* Whole stack: preprocessing data, model data, deploy model in application/cloud

### GPU/TPU

* Graphic Processing Unit
    * PyTorch enables to leverage GPU through interface - CUDA
* Tensor Processing Unit
    * ML & DL deals a lot with tensors

## What are Tensors?

* The data that is numerical encoded, then pass into Neural Network
* The data that is a representation output that pass out by Neural Network
    * They are **Tensors**
    * Tensors could be any representation of numbers
    
* Data turn into **tensors**, pass into Neural Networks, then **tensors** being pass out.

## Notebook Covering

* PyTorch Basics & Fundamentals (dealing with tensors & tensor operations)
* Preprocessing data (getting it into tensors)
* Building & using pretrained deep learning models
* Fitting a model to the data (learning patterns)
* Making predictions with a model (using patterns)
* Evaluating model predictions
* Saving & loading models
* Using a trained model to make predictions on custom data

<hr />

In [4]:
!nvidia-smi

Fri Jan 27 16:46:36 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.69       Driver Version: 511.69       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:02:00.0 Off |                  N/A |
| N/A   47C    P0    N/A /  N/A |      0MiB /  2048MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

C:\Users\linta\anaconda3\envs\data_science_playground\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
print(f'PyTorch version: {torch.__version__}')
print('*' *10)
print(f'_CUDA version: ')
!nvcc --version
print('*' *10)
print(f'CUDNN version: {torch.backends.cudnn.version()}')
print(f'Available GPU devices: {torch.cuda.device_count()}')
print(f'Device Name: {torch.cuda.get_device_name()}')

PyTorch version: 1.13.1+cu116
**********
_CUDA version: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
**********
CUDNN version: 8302
Available GPU devices: 1
Device Name: NVIDIA GeForce MX250


**CUDA enables us to run our code on Nvidia GPU**

### Introduction to Tensors

* A way to represent data, especially multi-dimension numeric data.

**Creating Tensors**
* PyTorch tensors are created using `torch.Tensor()`- https://pytorch.org/docs/stable/tensors.html

In [10]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
# Get tensor back as Python int
scalar.item()

7

In [14]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
# MATRIX - 2 square brackets
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [20]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# Tensor - 3 square brackets
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

**Random tensors**
* The way many neural networks learn is that they start with tensors full of random numbers, then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [36]:
# Create a random tensor with size (3, 4)
random_tensor = torch.rand((3, 4))
random_tensor

tensor([[0.4452, 0.7817, 0.7538, 0.5509],
        [0.0115, 0.7683, 0.9892, 0.2124],
        [0.4741, 0.6877, 0.9113, 0.1257]])

In [37]:
random_tensor.ndim

2

In [39]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

**Zeros & Ones**

In [40]:
# Creating a tensor of all zeros
# useful for masking out
zeros = torch.zeros((3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# Creating a tensors of all ones
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

**Range of tensors & tensors-like**

In [49]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**

**Note:** Tensor datatypes is one of the 3 big errors when running into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [51]:
# float 32 tensor
float32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                              dtype=None, # default dtype = float32
                              device='cuda', # default = cpu
                              requires_grad=False) # whether to track gradients with this tensors operations
float32_tensor

tensor([3., 6., 9.])

In [52]:
float32_tensor.dtype

torch.float32

In [53]:
float16_tensor = float32_tensor.type(torch.float16)

In [54]:
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [56]:
int32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int32_tensor

tensor([3, 6, 8], dtype=torch.int32)

**Getting information from tensors**
1. Get datatype from a tensor - `tensoor.dtype`
2. Get shape from a tensor - `tensor.shape`
3. Gett device from a tensor - `tensor.device`

In [57]:
# Create a tensor
some_tensor = torch.rand((3, 4))
some_tensor

tensor([[0.2885, 0.5922, 0.8182, 0.0246],
        [0.4398, 0.5844, 0.7943, 0.5265],
        [0.7892, 0.9175, 0.7537, 0.4830]])

In [58]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

**Manipulating Tensors (tensor operations)**

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [60]:
# Create a tensor & add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [61]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [62]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [63]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

**Matrix Multiplication**

2 main ways of performing multiplication in neural networks & deep learning:
1. Element-wise multiplication
<img src='resources/images/element_wise_multiplication.png' />
2. Matrix multiplication (Dot product)
<img src='resources/images/dot_product.png' />

There are two main rules that performing dot product needs to satisfy:
1. The **inner dimensions** must match:
    * `(3, 2) @ (3, 2)` - won't work
    * `(2, 3) @ (3, 2)` - will work
    
2. The resulting matrix has the shape of the **outer dimensions**:
    * `(2, 3) @ (3, 2)` -> `(2, 2)`
    * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [74]:
# Element-wise multiplication
tensor

tensor([1, 2, 3])

In [67]:
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [69]:
# Dot Product
torch.matmul(tensor, tensor)

tensor(14)

In [70]:
# Dot product by hand
1*1 + 2*2 + 3*3

14

**One of the most common errors in deep learning: Shape errors**

In [3]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # Same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [4]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Inner size must match

To fix the shape, we can use **transpose**

A **transpose** siwtches the axes or dimension of a tensor, matrix.

In [6]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [7]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [24]:
torch.mm(tensor_A, tensor_B.T).shape # Shape becomes the outer dimension

print(f'Original shapes:\ntensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'\nNew shapes:\ntensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}')
print(f'\nMultiplying: \n{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('-'*50)
print('Output:')
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print('-'*50)
print(f'Output shape: {output.shape}')

Original shapes:
tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes:
tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: 
torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
--------------------------------------------------
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
--------------------------------------------------
Output shape: torch.Size([3, 3])


**Tensor Aggregation: Finding the min, max, mean, sum, etc**

In [30]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [27]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [28]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [29]:
# Find the mean
torch.mean(x), x.mean() # --> Not the right datatype, requires a tensor of float32 to work

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [33]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [34]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

**Finding the Positional Min. & Max. of Tensors: argmin & argmax (Finding the index of max & min)**

In [36]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
x.argmin() # --> min. is at index: 0

tensor(0)

In [40]:
x[0]

tensor(0)

In [39]:
x.argmax() # --> max is at index: 9

tensor(9)

In [41]:
x[9]

tensor(90)

**Reshaping, Viewing, Stacking, Squeezing, Unsqueezing, Permuting**

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape, but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [44]:
# Creating a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7) # -> Needs to be compatible with the previous shape
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [46]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# Change the view
z = x.view(1, 9) # -> Similar to reshape, and view shares the same memory as the tensor
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
# Changing z changes x (view shares the same memory as  the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [52]:
# Stacking tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [59]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [64]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [65]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
# -> [colour_channels, height, width]
x_permuted = x_original.permute(2, 0, 1)

print(f'Previous shape: {x_original.shape}') # [height, width, colour_channels]
print(f'New shape: {x_permuted.shape}') # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Selecting Data from Tensors (Indexing)**

Similar to NumPy.

In [67]:
x_original.shape

torch.Size([224, 224, 3])

In [68]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0] # They share the same memory

(tensor(728218.), tensor(728218.))

In [71]:
# Create a tensor
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [72]:
x = x.reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Index on reshaped tensor

In [73]:
# On the 0th dimension
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
# Index on the middle bracket (dim=1)
x[0, 0] # same as x[0][0]

tensor([1, 2, 3])

In [83]:
# Index on the most inner bracket (last dimension)
x[0, 0, 0]

tensor(1)

In [79]:
# Use ':' too select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [80]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [81]:
# Get all values of 0th dimension but only the 1 index value of 1st & 2nd dimensions
x[:, 1, 1]

tensor([5])

In [82]:
# Get index 0 of 0th and 1st dimension & all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [84]:
# Q. Getting 9 from the matrix
x[0, 2, 2]

tensor(9)

In [90]:
# Q. Getting 3, 6, 9 from the matrix
x[:, :, 2]

tensor([[3, 6, 9]])

**PyTorch Tensors & NumPy**

NumPy - Numerical computing library

PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [91]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # reflects numpy's datatype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

* NumPy's default datatype - float64
* PyTorch's default datatype - float32

In [92]:
array.dtype

dtype('float64')

In [93]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor # new memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # reflects original dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor # new memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility: Trying to take random out of random**

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> repeat`

To reduce the randomness in neural networks & PyTorch, it comes the concept of a **random seed**.

Essentially, what the random seed does is 'flavour' the randomness.

In [110]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print('random_tensor_A:\n', random_tensor_A)
print('\nrandom_tensor_B:\n', random_tensor_B)
print('\n', random_tensor_A == random_tensor_B)

random_tensor_A:
 tensor([[0.1851, 0.9493, 0.1159, 0.8548],
        [0.5278, 0.3835, 0.0811, 0.3269],
        [0.7428, 0.1911, 0.0202, 0.4662]])

random_tensor_B:
 tensor([[0.2075, 0.8410, 0.5026, 0.4702],
        [0.0116, 0.9637, 0.3202, 0.1646],
        [0.2530, 0.6727, 0.8765, 0.2421]])

 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [128]:
# Set the random seed
torch.manual_seed(42)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(42)
random_tensor_D = torch.rand(3, 4)

print('random_tensor_C:\n', random_tensor_C)
print('\nrandom_tensor_D:\n', random_tensor_D)
print('\n', random_tensor_C == random_tensor_D)

random_tensor_C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

random_tensor_D:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running Tensors & PyTorch objects on GPUs (faster computations)**

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch

1. Getting a GPU

    1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
    2. Use own GPU - takes a little bit to setup & requires investment of purchasing a GPU, there is a lot of options, see this post for what option to choose: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
    3. Use cloud computing - GCP, AWS, Azure. These services allow you to rent computers on the cloud & access them.

For A & B, PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [129]:
!nvidia-smi

Sun Feb  5 15:14:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.69       Driver Version: 511.69       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:02:00.0 Off |                  N/A |
| N/A   40C    P0    N/A /  N/A |      0MiB /  2048MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

2. Check for GPU access with PyTorch

In [130]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch, since it is capable of running compute on GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

Eg. run on GPU if available, else default to CPU

In [131]:
# Setup device agnostic code - not sure if GPU is available, if it is, use it
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [132]:
# Count number of devices (GPU)
torch.cuda.device_count()

1

3. Putting tensors & models on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [134]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [136]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

4. Move tensors back to CPU
    * Note: NumPy only works with CPU

In [137]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [138]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [139]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')